<?php
$title = 'Edit product';
$this->headTitle($title);
?>
<h1 class="page-header"><?= $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url( 
        'cms-product',
        array(
            'action' => 'edit',
            'id'     => $id,
        )));
$form->get('submit')->setAttribute('class', 'btn btn-lg btn-default');
$form->prepare();

echo $this->form()->openTag($form),
     $this->formCollection($form),
     $this->form()->closeTag();
